img_shape: [375, 500, 3] # HxWxC
embedding_shape: [256, 64, 64] # CxHxW
mask_shape: [256, 256] # HxW
render_frame_shape: [320, 426] # HxW
max_steps: 5
# img_patch_size: 16
num_patches: 32  # along one axis
penalize_for_wrong_input: True
use_dice_score: False
render_mode: 'rgb_array'

target_categories : ['person', 'cat', 'dog', 'car', 'bicycle', 'bus']
dataset_config:
  type: 'coco'
  data_dir: 'data/coco-dataset'
  data_type: 'val2017'
  seed: 42
  max_instances: 3

sam_ckpt_fp: 'RepViT/sam/weights/repvit_sam.pt'
