img_shape: [640, 852, 3] # HxWxC
embedding_shape: [256, 64, 64] # CxHxW
mask_shape: [256, 256] # HxW
render_frame_shape: [320, 426] # HxW
tgt_class_idx: 3  # Rug index
max_steps: 5
img_patch_size: 64

img_dir: '/media/shantanu/Data/sam_align_data/images/train'
gt_mask_dir: '/media/shantanu/Data/sam_align_data/annotations/train'
sam_ckpt_fp: '/home/shantanu/Projects/RepViT/sam/weights/repvit_sam.pt'
