img_shape: [640, 852, 3] # HxWxC
embedding_shape: [256, 64, 64] # CxHxW
mask_shape: [256, 256] # HxW
render_frame_shape: [320, 426] # HxW
tgt_class_indices: [2, 3]  # indices to merge in the mask
max_steps: 5
# img_patch_size: 16
num_patches: 32  # along one axis 
render_mode: 'rgb_array'

img_dir: '/mnt/vol_c/cb_datasets/rug_dataset_full/segmentation_dataset/cb_seg_data63k/images/train'
gt_mask_dir: '/mnt/vol_c/cb_datasets/rug_dataset_full/segmentation_dataset/cb_seg_data63k/annotations/train'
sam_ckpt_fp: '/home/ubuntu/RepViT/sam/weights/repvit_sam.pt'
